config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'projects#index'
  end
  authenticated :user do
    resources :projects do
      member do
        patch '/add_user', to: 'projects#add_user'
        patch '/del_user', to: 'projects#del_user'
      end
      resources :bugs do
        member do
          patch '/assign_bug', to: 'bugs#assign_bug'
          patch '/mark_bug', to: 'bugs#mark_bug'
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include Pundit
end

app/models/bug.rb
class Bug < ApplicationRecord
  enum status: %i[new_bug started resolved]
  enum bug_type: %i[bug feature]

  belongs_to :project
  belongs_to :developer, class_name: 'User', foreign_key: :dev_id, optional: true
  belongs_to :user
  
  mount_uploader :avatar, AvatarUploader

  validates :title, presence: true, uniqueness: true
  validates :status, presence: true

  def dev
    developer.name if developer
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :user_projects, dependent: :delete_all
  has_many :users, through: :user_projects
  has_many :bugs, dependent: :delete_all
  validates :name, uniqueness: true, presence: true

  def qas
    users.where(role: 'qa')
  end

  def devs
    users.where(role: 'developer')
  end

  def managers
    users.where(role: 'manager')
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: %i[qa developer manager]

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :user_projects, dependent: :delete_all
  has_many :projects, through: :user_projects
  has_many :bugs, dependent: :delete_all
  has_many :bug_developer, class_name: 'Bug', foreign_key: :dev_id

  def manager?
    role == 'manager'
  end

  def qa?
    role == 'qa'
  end

  def developer?
    role == 'developer'
  end
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_in_path_for(resource)
    projects_path
  end

  def user_not_authorized
    redirect_to projects_path, flash: {error: 'You are not authorized to access this page.'}
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i[name email password password_confirmation role]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :find_project, except: %i[mark_bug assign_bug]
  before_action :find_bug, except: %i[index new create]
  before_action :authorize_bug_resource, except: %i[new index]
  before_action :authorize_project_resource, only: %i[show index]

  def index
    @bugs = @project.bugs
  end

  def show; end

  def new
    authorize Bug
    @bug = @project.bugs.build
  end

  def create
    bug = @project.bugs.build(bug_params)
    bug.user_id = current_user.id
    if bug.save
      redirect_to project_bugs_url, notice: 'new bug created'
    else
      redirect_to new_project_bug_url, flash: { error: 'bug title should be unique and non-empty' }
    end
  end

  def edit; end

  def update
    if @bug.update(bug_params)
      redirect_to project_bug_url, notice: 'bug is updated'
    else
      redirect_to edit_project_bug_url, flash: { error: 'bug title field should not be empty' }
    end
  end

  def destroy
    @bug.destroy
    redirect_to project_bugs_url, notice: 'bug is deleted'
  end

  def assign_bug
    @bug.update(developer: current_user, status: 'started')
    redirect_to project_bug_url, notice: 'bug has been assigne'
  end

  def mark_bug
    @bug.resolved!
    redirect_to project_bug_url, notice: 'bug has been resolved'
  end

  private

  def authorize_project_resource
    authorize @project, :show?
  end

  def authorize_bug_resource
    authorize @bug
  end

  def find_bug
    @bug = Bug.find(params[:id])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def bug_params
    params.require(:bug).permit(:title, :description, :deadline, :status, :bug_type, :avatar)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, except: %i[index new create]
  before_action :authorize_project_resource, except: %i[index new]

  def index
    @projects = Project.all.order('created_at DESC')
  end

  def new
    authorize Project
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to @project, notice: 'project is created'
    else
      redirect_to new_project_url, flash: { error: 'project name should be unique and non-empty' }
    end
  end

  def show
    @excluded_users = User.all.where.not(id: @project.users.ids)
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'project is updated'
    else
      redirect_to edit_project_url, flash: { error: 'project name field should not be empty' }
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path, notice: 'project is deleted'
  end

  def add_user
    @project.users << find_user
    redirect_to @project, notice: 'user is added to the project'
  end

  def del_user
    @project.users.delete(find_user)
    redirect_to @project, notice: 'user is removed from the project'
  end

  private

  def authorize_project_resource
    authorize @project
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_bug_form.html.erb
<%= form_for  [@project, @bug], :html => {:multipart => true} do |f|  %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar%>
  </div>
  <div class="row justify-content-md-center">
    <div class="field form-group col-md-3">
      <%= f.label "Type" %><br>
      <%= f.select :bug_type, options_for_select(["bug","feature"]), class: "form-control"
      %>
      </div>
  </div>      
  <div class="row justify-content-md-center">
    <div class="field form-group col-md-3">
      <%= f.label "Status" %><br>
      <%= f.select :status, options_for_select(["new_bug","started","resolved"]), class: "form-control" 
      %>
    </div>
  </div>
  <%= f.submit :class => 'button right' %>
<% end %>

app/views/bugs/edit.html.erb
<div class="bugform">
  <h1>Edit Bug</h1>
  <%= render 'bug_form'%>
</div>

app/views/bugs/index.html.erb
<div class="container	">
  <h1>All Bugs </h1>
  <% @project.bugs.each do |bug|%>
    <h2><%= bug.title %></h2>
    <div>
      <%= bug.description %>
    </div><br>
    <%= image_tag bug.avatar_url.to_s %><br>
    <p><strong>Status: </strong><%= bug.status %></p>
    <p><strong>Type: </strong><%= bug.bug_type %></p>
    <p><strong>Deadline: </strong><%= bug.deadline %></p><br> 
    <div>
      <%= link_to 'See bug details', project_bug_path(@project,bug) %>
    </div><hr>
  <% end %>
</div>

app/views/bugs/new.html.erb
<div class="bugform">
  <h1>Create Bug</h1>
  <%= render 'bug_form'%>
</div>

app/views/bugs/show.html.erb
<div class="container	">
  <h2><%= @bug.title %></h2>
  <div>
    <%= @bug.description %>
  </div><br>
  <%= image_tag @bug.avatar_url.to_s %>
  <p><strong>Status: </strong><%= @bug.status %></p>
  <p><strong>Created by: </strong><%= @bug.user.name  %></p>
  <p><strong>Role: </strong><%= @bug.user.role %></p>
  <p><strong>Deadline: </strong><%= @bug.deadline %></p>
  <p><strong>Assign To: </strong><%= @bug.dev %></p><br>
  <div>
    <li><%= link_to 'See All Bugs',project_bugs_path(@project,@bug) %></li>
    <li><%= link_to 'Edit Bug', edit_project_bug_path(@project,@bug) %></li>
    <% if !current_user.developer? %>
      <li><%= link_to 'Delete Bug', project_bug_path(@project,@bug), method: :delete, data: {confirm: "Are you sure?"} %></li>
    <% end %>

    <% if current_user.developer? && !@bug.dev %>
    <%= button_to 'Assign bug to himself',assign_bug_project_bug_path(@project ,@bug), method: :patch %>
    <% end %>

    <% if current_user.developer? && @bug.status != "resolved" && @bug.dev == current_user.name %>
      <%= button_to 'Resolve Bug',mark_bug_project_bug_path(@project ,@bug), method: :patch%>
    <% end %>
  </div>
  <hr>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <% if current_user.manager?%>
      <li><%= link_to 'Create Project', new_project_path %></li>
  <% end %>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to 'Home', projects_path, class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Signup BugZilla" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Signup BugZilla" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_project_form.html.erb
<%= form_for @project do |form|  %>
  <div class="form-group">
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="form-group">
    <%= form.label :Description %><br>
    <%= form.text_area :description %>
  </div>
  <%= form.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project </h1>
<!-- render Form -->
<%= render 'project_form'%>

app/views/projects/index.html.erb
<% if user_signed_in? %>
  <div class="container">
    <h1>All Projects </h1>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Project Title</th>
          <th scope="col">Description</th>
           <th scope="col">For more Details</th>
        </tr>
      </thead>
      <tbody>
        <% if !current_user.developer? %>
          <% @projects.each do |project|%>
            <tr>
              <td scope="row"><%= project.name %></td>
              <td><%= project.description %></td>
              <td><%= link_to 'See more', project %></td>
            </tr>
          <% end %>
          <% else %>
          <% current_user.projects.each do |project|%>
            <tr>
              <td scope="row"><%= project.name %></td>
              <td><%= project.description %></td>
              <td><%= link_to 'See more', project %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <h1 style="text-align: center;"><strong>BugZilla</strong> </h1>
<% end %>

app/views/projects/new.html.erb
<div class="authform">
  <h1>Create New Project </h1>
  <!-- render Form -->
  <%= render 'project_form'%>
</div>

app/views/projects/show.html.erb
<div class="container">
  <h1><%= @project.name %> </h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Operations</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @project.description %></td>
        <td>
          <% if current_user.manager? %>
            <ul><%= link_to 'Edit Project', edit_project_path(@project) %></ul><hr>
            <ul><%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?"}  %>
            </ul>
            <hr>
            <%end%>
            <ul><%= link_to 'View All Bugs',project_bugs_path(@project) %></ul>
            <% if !current_user.developer? %>
            <hr><ul><%= link_to 'Create New Bug', new_project_bug_path(@project) %></ul>
          <%end%>
        </td>
      </tr>
    </tbody> 
  </table><br><br>

  <h3>Developers</h3>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Role</th>
        <th scope="col">Email</th>
        <% if current_user.manager? %>
          <th scope="col">Click to Remove </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @project.devs.each do |user|%>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.role %></td>
          <td><%= user.email %></td>
          <% if current_user.manager? %>
           <td><%= link_to 'Remove', del_user_project_path(@project.id, user_id: user.id), method: :patch %></td> 
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table><br><br>

  <h3>QAs</h3>
  <table class="table table-bordered">
    <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Role</th>
          <th scope="col">Email</th>
          <% if current_user.manager? %>
          <th scope="col">Click to Remove </th>
          <% end %>
        </tr>
    </thead>
    <tbody>
      <% @project.qas.each do |user|%>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.role %></td>
          <td><%= user.email %></td>
          <% if current_user.manager? %>
            <td><%= link_to 'Remove', del_user_project_path(@project.id, user_id: user.id), method: :patch %></td> 
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table><br><br>

  <% if current_user.manager? %>
    <h3>Add Developer and QA to <strong><%= @project.name %> </strong> </h3>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Role</th>
          <th scope="col">Email</th>
          <th scope="col">Click to Add</th>
        </tr>
      </thead>
      <tbody>
        <%@excluded_users.each do |user|%>
          <% if !user.manager? %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.role %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Add', add_user_project_path(@project.id, user_id: user.id), method: :patch %></td> 
           </tr>
          <% end %>
        <% end %>
       </tbody>
    </table><br><br>
  <% end %>
</div>